#!/bin/bash

location="$1"
playlistURL="$2"

if [ $# -ne 2 ]
then
    echo "USAGE: $0 <location> <playlistURL>"
    exit 1
fi

if ! [ -d "env" ]
then
    python3 -m venv env || exit 1
fi

source env/bin/activate &&
pip install -r requirements.txt &&
python3 main.py "$location" "$playlistURL"